- name: test docker
  hosts: localhost
  gather_facts: false
  tasks:
    - name: create docker
      community.general.docker_container:
        name: limix-plantuml
        image: plantuml/plantuml-server:jetty
        auto_remove: true
        # command: whoami
        ports:
          - "9998:8080"
      environment:
        DOCKER_DEFAULT_PLATFORM: "linux/amd64"
    - name: add the container to inventory
      ansible.builtin.add_host:
        name: limix-plantuml
        ansible_connection: docker
- name: job
  hosts: limix-plantuml
  gather_facts: false
  tasks:
    - name: test whoami
      ansible.builtin.command: cat /etc/hosts
