name: first workflow
on: push

jobs:
  my-job:
    name: first job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        NAME: limix
      run: |
        echo $MY_VAR $NAME.
